name: Build and Publish Raspberry Pi ISO

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static qemu-utils xz-utils

      - name: Create iso directory
        run: |
          mkdir -p iso

      - name: download stock iso
        working-directory: build
        run: |
          curl https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2024-01-17/2024-01-16-raspios-bookworm-arm64-lite.img.xz -o iso/2024-01-16-raspios-bookworm-arm64-lite.img.xz

      - name: Build custom ISO
        working-directory: build
        run: |
          ls ../iso -lha
          ls -lha
          chmod +x build_iso.sh
          sudo ./build_iso.sh

      - name: Locate compressed image
        id: find_image
        run: |
          img=$(ls iso/*-border0-*.img.xz | head -n1)
          echo "path=$img" >> $GITHUB_OUTPUT
          echo "name=$(basename \"$img\")" >> $GITHUB_OUTPUT
      - name: Determine branch tag
        id: branch_tag
        run: |
          branch=${GITHUB_REF#refs/heads/}
          if [ "$branch" = "main" ]; then tag=stable; else tag=$branch; fi
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Rename ISO asset
        id: rename_image
        run: |
          old_path=${{ steps.find_image.outputs.path }}
          dir=$(dirname "$old_path")
          base=$(basename "$old_path")
          name=${base%.img.xz}
          new_name="${name}-${{ steps.branch_tag.outputs.tag }}.img.xz"
          mv "$old_path" "$dir/$new_name"
          echo "path=$dir/$new_name" >> $GITHUB_OUTPUT
          echo "name=$new_name" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ github.run_number }}
          release_name: "Raspberry Pi ISO Build #${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload ISO asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.rename_image.outputs.path }}
          asset_name: ${{ steps.rename_image.outputs.name }}
          asset_content_type: application/octet-stream